# Generated by Django 3.0.4 on 2021-01-28 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=256)),
                ('phone', models.CharField(max_length=10)),
                ('user_name', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('admin_point_of_contact', models.EmailField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=200)),
                ('license_type', models.CharField(choices=[('Production', 'Production'), ('Evaluation', 'Evaluation')], max_length=125)),
                ('created_time', models.DateTimeField()),
                ('expiration_time', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Licenseapp.Client')),
            ],
        ),
    ]
