# Generated by Django 3.0.4 on 2021-01-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licenseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='expiration_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
